capitals = {
    "Afghanistan": ["Кабул", "AF"],
    "Åland Islands": ["Мариехамн", "AX"],
    "Albania": ["Тирана", "AL"],
    "Algeria": ["Алжир", "DZ"],
    "American Samoa": ["Паго-Паго", "AS"],
    "Andorra": ["Андорра-ла-Велья", "AD"],
    "Angola": ["Луанда", "AO"],
    "Anguilla": ["Валли", "AI"],
    "Antarctica": ["Мак-Мердо", "AQ"],
    "Antigua and Barbuda": ["Сент-Джонс", "AG"],
    "Argentina": ["Буэнос-Айрес", "AR"],
    "Armenia": ["Ереван", "AM"],
    "Aruba": ["Ораньестад", "AW"],
    "Australia": ["Канберра", "AU"],
    "Austria": ["Вена", "AT"],
    "Azerbaijan": ["Баку", "AZ"],
    "Bahamas": ["Нассау", "BS"],
    "Bahrain": ["Манама", "BH"],
    "Bangladesh": ["Дакка", "BD"],
    "Barbados": ["Бриджтаун", "BB"],
    "Belarus": ["Минск", "BY"],
    "Belgium": ["Брюссель", "BE"],
    "Belize": ["Бельмопан", "BZ"],
    "Benin": ["Порто-Ново", "BJ"],
    "Bermuda": ["Гамильтон", "BM"],
    "Bhutan": ["Тхимпху", "BT"],
    "Bolivia": ["Сукре", "BO"],
    "Bonaire, Sint Eustatius, and Saba": ["Кралендейк", "BQ"],
    "Bosnia and Herzegovina": ["Сараево", "BA"],
    "Botswana": ["Габороне", "BW"],
    "Bouvet Island": ["Необитаем", "BV"],
    "Brazil": ["Бразилиа", "BR"],
    "British Indian Ocean Territory": ["Диего-Гарсия", "IO"],
    "British Virgin Islands": ["Род-Таун", "VG"],
    "Brunei": ["Бандар-Сери-Бегаван", "BN"],
    "Bulgaria": ["София", "BG"],
    "Burkina Faso": ["Уагадугу", "BF"],
    "Burundi": ["Гитега", "BI"],
    "Cabo Verde": ["Прая", "CV"],
    "Cambodia": ["Пномпень", "KH"],
    "Cameroon": ["Яунде", "CM"],
    "Canada": ["Оттава", "CA"],
    "Cayman Islands": ["Джорджтаун", "KY"],
    "Central African Republic": ["Банги", "CF"],
    "Chad": ["Нджамена", "TD"],
    "Chile": ["Сантьяго", "CL"],
    "China": ["Пекин", "CN"],
    "Christmas Island": ["Флайинг-Фиш-Коув", "CX"],
    "Cocos (Keeling) Islands": ["Уэст-Айленд", "CC"],
    "Colombia": ["Богота", "CO"],
    "Comoros": ["Морони", "KM"],
    "Congo Republic": ["Браззавиль", "CG"],
    "Cook Islands": ["Аваруа", "CK"],
    "Costa Rica": ["Сан-Хосе", "CR"],
    "Croatia": ["Загреб", "HR"],
    "Cuba": ["Гавана", "CU"],
    "Curaçao": ["Виллемстад", "CW"],
    "Cyprus": ["Никосия", "CY"],
    "Czechia": ["Прага", "CZ"],
    "Denmark": ["Копенгаген", "DK"],
    "Djibouti": ["Джибути", "DJ"],
    "Dominica": ["Розо", "DM"],
    "Dominican Republic": ["Санто-Доминго", "DO"],
    "DR Congo": ["Киншаса", "CD"],
    "Ecuador": ["Кито", "EC"],
    "Egypt": ["Каир", "EG"],
    "El Salvador": ["Сан-Сальвадор", "SV"],
    "Equatorial Guinea": ["Малабо", "GQ"],
    "Eritrea": ["Асмэра", "ER"],
    "Estonia": ["Таллин", "EE"],
    "Eswatini": ["Мбабане", "SZ"],
    "Ethiopia": ["Аддис-Абеба", "ET"],
    "Falkland Islands": ["Стэнли", "FK"],
    "Faroe Islands": ["Торсхавн", "FO"],
    "Federated States of Micronesia": ["Паликир", "FM"],
    "Fiji": ["Сува", "FJ"],
    "Finland": ["Хельсинки", "FI"],
    "France": ["Париж", "FR"],
    "French Guiana": ["Кайенна", "GF"],
    "French Polynesia": ["Папеэте", "PF"],
    "French Southern Territories": ["Порт-о-Франсе", "TF"],
    "Gabon": ["Либревиль", "GA"],
    "Gambia": ["Банжул", "GM"],
    "Georgia": ["Тбилиси", "GE"],
    "Germany": ["Берлин", "DE"],
    "Ghana": ["Аккра", "GH"],
    "Gibraltar": ["Гибралтар", "GI"],
    "Greece": ["Афины", "GR"],
    "Greenland": ["Нуук", "GL"],
    "Grenada": ["Сент-Джорджес", "GD"],
    "Guadeloupe": ["Бас-Тер", "GP"],
    "Guam": ["Хагатна", "GU"],
    "Guatemala": ["Гватемала", "GT"],
    "Guernsey": ["Сент-Питер-Порт", "GG"],
    "Guinea": ["Конакри", "GN"],
    "Guinea-Bissau": ["Бисау", "GW"],
    "Guyana": ["Джорджтаун", "GY"],
    "Haiti": ["Порт-о-Пренс", "HT"],
    "Heard and McDonald Islands": ["Необитаем", "HM"],
    "Honduras": ["Тегусигальпа", "HN"],
    "Hong Kong": ["Гонконг", "HK"],
    "Hungary": ["Будапешт", "HU"],
    "Iceland": ["Рейкьявик", "IS"],
    "India": ["Дели (Нью-Дели)", "IN"],
    "Indonesia": ["Джакарта", "ID"],
    "Iran": ["Тегеран", "IR"],
    "Iraq": ["Багдад", "IQ"],
    "Ireland": ["Дублин", "IE"],
    "Isle of Man": ["Дуглас", "IM"],
    "Israel": ["Иерусалим", "IL"],
    "Italy": ["Рим", "IT"],
    "Ivory Coast": ["Ямусукро", "CI"],
    "Jamaica": ["Кингстон", "JM"],
    "Japan": ["Токио", "JP"],
    "Jersey": ["Сент-Хельер", "JE"],
    "Jordan": ["Амман", "JO"],
    "Kazakhstan": ["Астана", "KZ"],
    "Kenya": ["Найроби", "KE"],
    "Kiribati": ["Южная Тарава (Баирики)", "KI"],
    "Kosovo": ["Приштина", "XK"],
    "Kuwait": ["Эль-Кувейт", "KW"],
    "Kyrgyzstan": ["Бишкек", "KG"],
    "Laos": ["Вьентьян", "LA"],
    "Latvia": ["Рига", "LV"],
    "Lebanon": ["Бейрут", "LB"],
    "Lesotho": ["Масеру", "LS"],
    "Liberia": ["Монровия", "LR"],
    "Libya": ["Триполи", "LY"],
    "Liechtenstein": ["Вадуц", "LI"],
    "Lithuania": ["Вильнюс", "LT"],
    "Luxembourg": ["Люксембург", "LU"],
    "Macao": ["Макао", "MO"],
    "Madagascar": ["Антананариву", "MG"],
    "Malawi": ["Лилонгве", "MW"],
    "Malaysia": ["Куала-Лумпур", "MY"],
    "Maldives": ["Мале", "MV"],
    "Mali": ["Бамако", "ML"],
    "Malta": ["Валлетта", "MT"],
    "Marshall Islands": ["Маджуро", "MH"],
    "Martinique": ["Фор-де-Франс", "MQ"],
    "Mauritania": ["Нуакшот", "MR"],
    "Mauritius": ["Порт-Луи", "MU"],
    "Mayotte": ["Мамудзу", "YT"],
    "Mexico": ["Мехико", "MX"],
    "Moldova": ["Кишинёв", "MD"],
    "Monaco": ["Монако", "MC"],
    "Mongolia": ["Улан-Батор", "MN"],
    "Montenegro": ["Подгорица", "ME"],
    "Montserrat": ["Плимут", "MS"],
    "Morocco": ["Рабат", "MA"],
    "Mozambique": ["Мапуту", "MZ"],
    "Myanmar": ["Нейпьидо", "MM"],
    "Namibia": ["Виндхук", "NA"],
    "Nauru": ["Ярен", "NR"],
    "Nepal": ["Катманду", "NP"],
    "New Caledonia": ["Нумеа", "NC"],
    "New Zealand": ["Веллингтон", "NZ"],
    "Nicaragua": ["Манагуа", "NI"],
    "Niger": ["Ниамей", "NE"],
    "Nigeria": ["Абуджа", "NG"],
    "Niue": ["Алофи", "NU"],
    "Norfolk Island": ["Кингстон", "NF"],
    "North Korea": ["Пхеньян", "KP"],
    "North Macedonia": ["Скопье", "MK"],
    "Northern Mariana Islands": ["Сайпан", "MP"],
    "Norway": ["Осло", "NO"],
    "Oman": ["Маскат", "OM"],
    "Pakistan": ["Исламабад", "PK"],
    "Palau": ["Нгерулмуд", "PW"],
    "Palestine": ["Рамалла", "PS"],
    "Panama": ["Панама", "PA"],
    "Papua New Guinea": ["Порт-Морсби", "PG"],
    "Paraguay": ["Асунсьон", "PY"],
    "Peru": ["Лима", "PE"],
    "Philippines": ["Манила", "PH"],
    "Pitcairn Islands": ["Адамстаун", "PN"],
    "Poland": ["Варшава", "PL"],
    "Portugal": ["Лиссабон", "PT"],
    "Puerto Rico": ["Сан-Хуан", "PR"],
    "Qatar": ["Доха", "QA"],
    "Réunion": ["Сен-Дени", "RE"],
    "Romania": ["Бухарест", "RO"],
    "Russia": ["Москва", "RU"],
    "Rwanda": ["Кигали", "RW"],
    "Saint Barthélemy": ["Густавия", "BL"],
    "Saint Helena": ["Джеймстаун", "SH"],
    "Saint Lucia": ["Кастри", "LC"],
    "Saint Martin": ["Мариго", "MF"],
    "Saint Pierre and Miquelon": ["Сен-Пьер", "PM"],
    "Samoa": ["Апиа", "WS"],
    "San Marino": ["Сан-Марино", "SM"],
    "São Tomé and Príncipe": ["Сан-Томе", "ST"],
    "Saudi Arabia": ["Эр-Рияд", "SA"],
    "Senegal": ["Дакар", "SN"],
    "Serbia": ["Белград", "RS"],
    "Seychelles": ["Виктория", "SC"],
    "Sierra Leone": ["Фритаун", "SL"],
    "Singapore": ["Сингапур", "SG"],
    "Sint Maarten": ["Филипсбург", "SX"],
    "Slovakia": ["Братислава", "SK"],
    "Slovenia": ["Любляна", "SI"],
    "Solomon Islands": ["Хониара", "SB"],
    "Somalia": ["Могадишо", "SO"],
    "South Africa": ["Претория", "ZA"],
    "South Georgia and the South Sandwich Islands": ["Кинг-Эдуард-Пойнт", "GS"],
    "South Korea": ["Сеул", "KR"],
    "South Sudan": ["Джуба", "SS"],
    "Spain": ["Мадрид", "ES"],
    "Sri Lanka": ["Шри-Джаяварденепура-Котте", "LK"],
    "St Kitts and Nevis": ["Бастер", "KN"],
    "St Vincent and Grenadines": ["Кингстаун", "VC"],
    "Sudan": ["Хартум", "SD"],
    "Suriname": ["Парамарибо", "SR"],
    "Svalbard and Jan Mayen": ["Лонгйир", "SJ"],
    "Sweden": ["Стокгольм", "SE"],
    "Switzerland": ["Берн", "CH"],
    "Syria": ["Дамаск", "SY"],
    "Taiwan": ["Тайбэй", "TW"],
    "Tajikistan": ["Душанбе", "TJ"],
    "Tanzania": ["Додома", "TZ"],
    "Thailand": ["Бангкок", "TH"],
    "The Netherlands": ["Амстердам", "NL"],
    "Timor-Leste": ["Дили", "TL"],
    "Togo": ["Ломе", "TG"],
    "Tokelau": ["Атафу", "TK"],
    "Tonga": ["Нукуалофа", "TO"],
    "Trinidad and Tobago": ["Порт-оф-Спейн", "TT"],
    "Tunisia": ["Тунис", "TN"],
    "Türkiye": ["Анкара", "TR"],
    "Turkmenistan": ["Ашхабад", "TM"],
    "Turks and Caicos Islands": ["Коберн-Таун", "TC"],
    "Tuvalu": ["Фунафути", "TV"],
    "U.S. Outlying Islands": ["Внешние малые острова США", "UM"],
    "U.S. Virgin Islands": ["Шарлотта-Амалия", "VI"],
    "Uganda": ["Кампала", "UG"],
    "Ukraine": ["Киев", "UA"],
    "United Arab Emirates": ["Абу-Даби", "AE"],
    "United Kingdom": ["Лондон", "UK"],
    "United States": ["Вашингтон", "US"],
    "Unknown": ["Unknown", "??"],
    "Uruguay": ["Монтевидео", "UY"],
    "Uzbekistan": ["Ташкент", "UZ"],
    "Vanuatu": ["Порт-Вила", "VU"],
    "Vatican City": ["Ватикан", "VA"],
    "Venezuela": ["Каракас", "VE"],
    "Vietnam": ["Ханой", "VN"],
    "Wallis and Futuna": ["Мата-Уту", "WF"],
    "Western Sahara": ["Тифарити", "EH"],
    "Yemen": ["Сана", "YE"],
    "Zambia": ["Лусака", "ZM"],
    "Zimbabwe": ["Хараре", "ZW"]
}